django_instagram/django_ig/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('feeds.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_instagram/feeds/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_user, name='login'),
    path('signout/', views.signout, name='signout'),
    path('signup_success/', views.signup_success, name='signup_success'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('profile/<str:username>/edit/', views.profile_settings, name='profile_settings'),
    path('profile/<str:username>/followers/', views.followers, name='followers'),
    path('profile/<str:username>/following/', views.following, name='following'),
    path('post/<int:pk>/', views.post, name='post'),
    path('post/', views.post_picture, name='post_picture'),
    path('explore/', views.explore, name='explore'),
    path('notifications/', views.notifications, name='notifications'),
    path('inbox/', views.inbox, name='inbox'),
    path('inbox/<str:label>/', views.chat, name='chat'),
    path('new_chat/', views.new_chat, name='new_chat'),
    path('new_chat/<str:username>/', views.new_chat_create, name='new_chat_create'),
    path('post/<int:pk>/likes/', views.likes, name='likes'),
    path('like/', views.add_like, name='like'),
    path('comment/', views.add_comment, name='comment'),
    path('follow_toggle/', views.follow_toggle, name='follow_toggle'),

]

django_instagram/feeds/models.py
from datetime import datetime
from django.db import models
from django.contrib.auth.models import User, BaseUserManager, AbstractBaseUser, PermissionsMixin
from django.db.models.signals import post_save
from django.dispatch import receiver

from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

from datetime import datetime

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    followers = models.ManyToManyField('UserProfile',
                                        related_name="followers_profile",
                                        blank=True)
    following = models.ManyToManyField('UserProfile',
                                        related_name="following_profile",
                                        blank=True)
    profile_pic = ProcessedImageField(upload_to='profile_pics',
                                format='JPEG',
                                options={ 'quality': 100},
                                null=True,
                                blank=True)

    description = models.CharField(max_length=200, null=True, blank=True)

    def get_number_of_followers(self):
        print(self.followers.count())
        if self.followers.count():
            return self.followers.count()
        else:
            return 0

    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            UserProfile.objects.create(user=instance)

    def get_number_of_following(self):
        if self.following.count():
            return self.following.count()
        else:
            return 0

    def __str__(self):
        return self.user.username

class IGPost(models.Model):
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=100)
    image = ProcessedImageField(upload_to='posts',
                                #processors=[ResizeToFill(200,200)],
                                format='JPEG',
                                options={ 'quality': 100})
    posted_on = models.DateTimeField(default=datetime.now)

    def get_number_of_likes(self):
        return self.like_set.count()

    def get_number_of_comments(self):
        return self.comment_set.count()

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey('IGPost', on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    comment = models.CharField(max_length=100)
    posted_on = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return self.comment


class Like(models.Model):
    post = models.ForeignKey('IGPost', on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)

    class Meta:
        unique_together = ("post", "user")

    def __str__(self):
        return 'Like: ' + self.user.username + ' ' + self.post.title


class Room(models.Model):
    label = models.SlugField(unique=True)
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name="receiver")
    sender = models.ForeignKey(User,on_delete=models.CASCADE, related_name="sender")

    def get_last_message(self):
        message = Message.objects.filter(room=self).last()
        return message.text if message else ""

    def get_last_message_timestamp(self):
        message = Message.objects.filter(room=self).last()
        return message.timestamp if message else ""

    def __str__(self):
        return self.label


class Message(models.Model):
    room = models.ForeignKey(Room,on_delete=models.CASCADE, related_name="messages")
    sender = models.ForeignKey(User,on_delete=models.CASCADE)
    text = models.TextField()
    timestamp = models.DateTimeField(default=datetime.now, db_index=True)

    def __str__(self):
        return self.text + " S:" + self.sender.username

django_instagram/feeds/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from imagekit.forms import ProcessedImageField

from . models import IGPost, UserProfile, Comment, Like


class UserCreateForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class PostPictureForm(ModelForm):
    class Meta:
        model = IGPost
        fields = ['title', 'image']


class ProfileEditForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_pic', 'description']


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']

django_instagram/feeds/views.py
import datetime
from django.http import JsonResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse
from django.views.generic.edit import CreateView

from imagekit.models import ProcessedImageField
from annoying.decorators import ajax_request

from . forms import UserCreateForm, PostPictureForm, ProfileEditForm, CommentForm
from . models import UserProfile, IGPost, Comment, Like, Message, Room


def index(request):
    if not request.user.is_authenticated:
        return redirect('login')  # ← и не забудь return!
    if not hasattr(request.user, 'userprofile'):
        UserProfile.objects.create(user=request.user)

    users_followed = request.user.userprofile.following.all()
    posts = IGPost.objects.filter(
                user_profile__in=users_followed).order_by('-posted_on')

    return render(request, 'feeds/index.html', {
        'posts': posts
    })


def explore(request):
    random_posts = IGPost.objects.all().order_by('?')[:40]

    context = {
        'posts': random_posts
    }
    return render(request, 'feeds/explore.html', context)


@login_required
def notifications(request):
    context = {}
    return render(request, 'feeds/notifications.html', context)


@login_required
def inbox(request):
    user = request.user
    rooms = Room.objects.filter(Q(receiver=user) | Q(sender=user))
    context = {
        'rooms': rooms
    }
    return render(request, 'feeds/inbox.html', context)


@login_required
def chat(request, label):
    user = request.user
    room = Room.objects.get(label=label)
    messages = reversed(room.messages.order_by('-timestamp')[:50])

    context = {
        'room': room,
        'messages': messages
    }
    return render(request, 'feeds/chat.html', context)


@login_required
def new_chat(request):
    profiles = request.user.userprofile.following.all()
    context = {
        'profiles': profiles
    }
    return render(request, 'feeds/new_chat.html', context)


@login_required
def new_chat_create(request, username):
    user_to_message = User.objects.get(username=username)
    room_label = request.user.username + '_' + user_to_message.username

    try:
        does_room_exist = Room.objects.get(label=room_label)
    except:
        room = Room(label=room_label, receiver=user_to_message,
                    sender=request.user)
        room.save()

    return redirect('chat', label=room_label)


def signup(request):
    if request.method == 'POST':
        form = UserCreateForm(request.POST)
        if form.is_valid():
            user = form.save()
            user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password1'])
            if user:
                login(request, user)
                print("User logged in successfully.")  # Добавьте для отладки
                return redirect('index')
            else:
                print("Authentication failed.")  # Если аутентификация не удалась
        else:
            print("Form is not valid.")  # Если форма не прошла валидацию
    else:
        form = UserCreateForm()
    return render(request, 'feeds/signup.html', {'form': form})

from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect



def login_user(request):
    form = AuthenticationForm()

    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)  # передаем request в форму
        if form.is_valid():  # если форма прошла валидацию
            user = form.get_user()  # получаем пользователя из формы
            login(request, user)  # авторизуем пользователя
            return redirect('index')  # переадресуем на главную страницу

    return render(request, 'feeds/login.html', {'form': form})

def signout(request):
    logout(request)
    return redirect('index')


def signup_success(request):
    return render(request, 'feeds/signup_success.html')


def profile(request, username):
    user = User.objects.get(username=username)
    if not user:
        return redirect('index')

    profile = UserProfile.objects.get(user=user)
    context = {
        'username': username,
        'user': user,
        'profile': profile
    }
    return render(request, 'feeds/profile.html', context)


@login_required
def profile_settings(request, username):
    user = User.objects.get(username=username)
    if request.user != user:
        return redirect('index')

    if request.method == 'POST':
        print(request.POST)
        form = ProfileEditForm(request.POST, instance=user.userprofile, files=request.FILES)
        if form.is_valid():
            form.save()
            return redirect(reverse('profile', kwargs={'username': user.username}))
    else:
        form = ProfileEditForm(instance=user.userprofile)

    context = {
        'user': user,
        'form': form
    }
    return render(request, 'feeds/profile_settings.html', context)


def followers(request, username):
    user = User.objects.get(username=username)
    user_profile = UserProfile.objects.get(user=user)
    profiles = user_profile.followers.all

    context = {
        'header': 'Followers',
        'profiles': profiles,
    }

    return render(request, 'feeds/follow_list.html', context)


def following(request, username):
    user = User.objects.get(username=username)
    user_profile = UserProfile.objects.get(user=user)
    profiles = user_profile.following.all

    context = {
        'header': 'Following',
        'profiles': profiles
    }
    return render(request, 'feeds/follow_list.html', context)



@login_required
def post_picture(request):
    if request.method == 'POST':
        form = PostPictureForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            post = IGPost(user_profile=request.user.userprofile,
                          title=request.POST['title'],
                          image=request.FILES['image'],
                          posted_on=datetime.datetime.now())
            post.save()
            return redirect(reverse('profile', kwargs={'username': request.user.username}))
    else:
        form = PostPictureForm()

    context = {
        'form': form
    }
    return render(request, 'feeds/post_picture.html', context)


def post(request, pk):
    post = IGPost.objects.get(pk=pk)
    try:
        like = Like.objects.get(post=post, user=request.user)
        liked = 1
    except:
        like = None
        liked = 0

    context = {
        'post': post,
        'liked': liked
    }
    return render(request, 'feeds/post.html', context)


def likes(request, pk):
    #likes = IGPost.objects.get(pk=pk).like_set.all()
    #profiles = [like.user.userprofile for like in likes]

    post = IGPost.objects.get(pk=pk)
    profiles = Like.objects.filter(post=post)

    context = {
        'header': 'Likes',
        'profiles': profiles
    }
    return render(request, 'feeds/follow_list.html', context)


@ajax_request
@login_required
def add_like(request):
    post_pk = request.POST.get('post_pk')
    post = IGPost.objects.get(pk=post_pk)
    try:
        like = Like(post=post, user=request.user)
        like.save()
        result = 1
    except Exception as e:
        like = Like.objects.get(post=post, user=request.user)
        like.delete()
        result = 0

    return {
        'result': result,
        'post_pk': post_pk
    }


@ajax_request
@login_required
def add_comment(request):
    comment_text = request.POST.get('comment_text')
    post_pk = request.POST.get('post_pk')
    post = IGPost.objects.get(pk=post_pk)
    commenter_info = {}

    try:
        comment = Comment(comment=comment_text, user=request.user, post=post)
        comment.save()

        username = request.user.username
        profile_url = reverse('profile', kwargs={'username': request.user})

        commenter_info = {
            'username': username,
            'profile_url': profile_url,
            'comment_text': comment_text
        }


        result = 1
    except Exception as e:
        print(e)
        result = 0

    return {
        'result': result,
        'post_pk': post_pk,
        'commenter_info': commenter_info
    }


@ajax_request
@login_required
def follow_toggle(request):
    user_profile = UserProfile.objects.get(user=request.user)
    follow_profile_pk = request.POST.get('follow_profile_pk')
    follow_profile = UserProfile.objects.get(pk=follow_profile_pk)

    try:
        if user_profile != follow_profile:
            if request.POST.get('type') == 'follow':
                user_profile.following.add(follow_profile)
                follow_profile.followers.add(user_profile)
            elif request.POST.get('type') == 'unfollow':
                user_profile.following.remove(follow_profile)
                follow_profile.followers.remove(user_profile)
            user_profile.save()
            result = 1
        else:
            result = 0
    except Exception as e:
        print(e)
        result = 0

    return {
        'result': result,
        'type': request.POST.get('type'),
        'follow_profile_pk': follow_profile_pk
    }

django_instagram/feeds/templates/feeds/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>django_ig</title>
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/font-awesome-4.6.3/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
  </head>
  <body class="{% block body_class_override %}{% endblock %}">
    {% include 'feeds/nav.html' %}

    <div class="content-wrapper">
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </div>


    <script type="text/javascript" src="{% static 'js/jquery-3.1.0.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/ajax-csrf-auth.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/index.js' %}"></script>
    {% block extrascript %}
    {% endblock %}


  </body>
</html>

django_instagram/feeds/templates/feeds/chat.html
{% extends 'feeds/base.html' %}

{% load static %}

{% block body_class_override %}white{% endblock %}
{% block content %}
  <div id="messages">
    {% for message in messages %}
      <div class="{% if request.user == message.sender %}message-sent{% else %}message-received{% endif %}">
        {% if request.user != message.sender %}<div class="sender">{{ message.sender.username }}</div>{% endif %}
        <div class="text">{{ message.text }}</div>
      </div>
    {% endfor %}
  </div>

  <form id="chatForm">
    <div id="chatData" style="display: none">
      <span id="session-key">{{ request.session.session_key }}</span>
      <span id="user">{{ request.user.username }}</span>
    </div>
    <input type="text" id="messageInput" placeholder="Write a message...">
  </form>

{% endblock %}


{% block extrascript %}
<script src="{% static 'js/inbox.js' %}"></script>
{% endblock %}

django_instagram/feeds/templates/feeds/explore.html
{% extends 'feeds/base.html' %}

{% block content %}
<div class="row" id="explore">
  {% for post in posts reversed %}
    <div class="col-xs-4 col-sm-3">
      <div class="picture-square" style="background-image: url({{ post.image.url }})">
        <a href="{% url 'post' post.pk %}">
          <div class="content"></div>
        </a>
      </div>
    </div>
  {% endfor %}
</div>
{% endblock %}

django_instagram/feeds/templates/feeds/inbox.html
{% extends 'feeds/base.html' %}

{% load static custom_tags %}

{% block content %}
<div class="row">

  <div class="controls desktop">
    <div class="right">
      <a class="new-message" href="{% url 'new_chat' %}"><i class="fa fa-plus active"></i></a>
    </div>
  </div>
  {% for room in rooms %}
    {% find_proper_user request.user room as user_for_display %}
    <div class="card__panel-head message">
      <a href="{% url 'chat' room.label %}">
        <div class="poster__info">
          {% if user_for_display.userprofile.profile_pic %}
            <img class="picture-circle--medium" src="{{ user_for_display.userprofile.profile_pic.url }}">
          {% else %}
            <img class="picture-circle--medium" src="{% static 'images/profile_placeholder.jpg' %}">
          {% endif %}
          <div class="message-info">
            <p class="username">{{ user_for_display.username }}</p>
            <p class="text">{{ room.get_last_message|truncatechars:30 }}</p>
          </div>
          <div class="timestamp">{{ room.get_last_message_timestamp }}</div>
        </div>
      </a>
    </div>
  {% endfor %}

</div>

{% endblock %}

django_instagram/feeds/templates/feeds/index.html
{% extends 'feeds/base.html' %}

{% load static custom_tags %}

{% block content %}
    <div class="cards-listing">
        {% for post in posts %}
            <div class="row">
                <div class="card view-update {{ post.pk }}">
                    <div class="card__panel-head">
                        <div class="poster__info">
                            <a href="{% url 'profile' post.user_profile.user.username %}" class="poster__name">
                              {% if post.user_profile.profile_pic %}
                                <img class="poster__profilepic" src="{{ post.user_profile.profile_pic.url }}">
                              {% else %}
                                <img class="poster__profilepic" src="{% static 'images/profile_placeholder.jpg' %}">
                              {% endif %}
                              {{ post.user_profile.user.username }}
                            </a>
                            <span class="poster__timestamp">
                                {{ post.posted_on|timesince }}
                            </span>
                        </div>
                    </div>
                    <img class="card__main-image" src="{{ post.image.url }}">
                    <div class="card__panel-body">
                        <a href="{% url 'likes' post.pk %}">
                          <div class="likes">
                            {% if post.get_number_of_likes %}
                                {{ post.get_number_of_likes }} like{% if post.get_number_of_likes > 1 %}s{% endif %}
                            {% endif %}
                          </div>
                        </a>
                        <ul class="comment-list">
                          <li class="comment-list__comment">
                            <a class="user" href="{% url 'profile' post.user_profile.user.username %}">
                              {{ post.user_profile.user.username }}
                            </a>
                            <span class="comment">{{ post.title | parse_hashtags | safe }}</span>
                          </li>
                          <a class="view-more"></a>
                          {% for comment in post.comment_set.all %}
                            <li class="comment-list__comment">
                              <a href="{% url 'profile' comment.user.username %}" class="user">
                                {{ comment.user.username }}
                              </a>
                              <span class="comment">{{ comment.comment }}</span>
                            </li>
                          {% endfor %}
                        </ul>
                        {% if request.user.is_authenticated %}
                          <section class="input-row">
                            <i class="fa {% has_user_liked_post post request.user %} submit-like" aria-hidden="true"></i>
                            <div class="comment-input-wrapper">
                              <input class="add-comment" type="text" placeholder="Add a comment...">
                            </div>
                            <div class="hidden-data {{ post.pk }}" style="display: none;">
                              <span class="post-pk">{{ post.pk }}</span>
                            </div>
                          </section>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

django_instagram/feeds/templates/feeds/login.html
{% extends 'feeds/base.html' %}

{% load static custom_tags %}

{% block body_class_override %}white{% endblock %}
{% block content %}
<div class="row auth-form">
  <div class="col-xs-12">
    <form action="{% url 'login' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
          {{ form.username.label }}
          {{ form.username|addClass:"form-control" }}
          {{ form.username.errors }}
        </div>
        <div class="form-group">
          {{ form.password.label }}
          {{ form.password|addClass:"form-control" }}
          {{ form.password.errors }}
        </div>

        <button class="btn btn-default">Login</button>
        <div class="text-center help-text">
          Don't have an account? <a href="{% url 'signup' %}">Register</a>
        </div>
    </form>
  </div>
</div>
{% endblock %}

django_instagram/feeds/templates/feeds/new_chat.html
{% extends 'feeds/base.html' %}

{% load static custom_tags %}

{% block content %}
<div class="follow__wrapper row">
  <div class="follow__heading">
    <a class="back-button"><i class="fa fa-arrow-left active"></i></a>Select a profile
  </div>
  {% for profile in profiles %}
    <div class="follow__card" id="{{ profile.pk }}">
      {% if profile.profile_pic %}
        <img class="picture-circle--small" src="{{ profile.profile_pic.url }}">
      {% else %}
        <img class="picture-circle--small" src="{% static 'images/profile_placeholder.jpg' %}">
      {% endif %}
      <a href="{% url 'profile' profile.user.username %}">{{ profile.user.username }}</a>

      {% if request.user.is_authenticated and profile != request.user.userprofile %}
        <div class="follow-toggle__container">
          <a href="{% url 'new_chat_create' profile.user.username %}">
            <button class="btn btn-primary generic-button">Message</button>
          </a>
        </div>
      {% endif %}
    </div>
  {% endfor %}
</div>
{% endblock %}

django_instagram/feeds/templates/feeds/notifications.html
{% extends 'feeds/base.html' %}

{% block content %}
notifications here
{% endblock %}

django_instagram/feeds/templates/feeds/post_picture.html
{% extends 'feeds/base.html' %}

{% block content %}
<div class="row">
  <div class="col-xs-12">
    <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}

      <label>
        {{ form.title.label }}
        {{ form.title }}
        {{ form.title.errors }}
      </label>
      <label>
        {{ form.image.label }}
        {{ form.image }}
        {{ form.image.errors }}
      </label>
      <button type="submit" class="btn btn-default">Submit</button>
    </form>
  </div>
</div>
{% endblock %}

django_instagram/feeds/templates/feeds/profile.html
{% extends 'feeds/base.html' %}

{% load static custom_tags %}

{% block content %}
<div class="profile">
  <div class="profile__head">
    <div class="row">
      <div class="col-xs-4 left">
        {% if profile.profile_pic %}
          <img class="picture-circle" src="{{ profile.profile_pic.url }}">
        {% else %}
          <img class="picture-circle" src="{% static 'images/profile_placeholder.jpg' %}">
        {% endif %}
      </div>
      <div class="col-xs-8 right">
        <div class="name-buttons">
          <h1 class="username">{{ user.username }}</h1>
          {% if request.user == user %}
            <a class="edit-desktop" href="{% url 'profile_settings' user.username %}">
              <button class="edit-profile">Edit Profile</button>
            </a>
            <div class="options-bubbles" type="button" data-toggle="modal" data-target="#logoutModal">
              <p class="bubble"></p>
              <p class="bubble"></p>
              <p class="bubble"></p>
            </div>
          {% elif request.user.is_authenticated %}
          <div class="follow-toggle__container">
            {% is_following request.user.userprofile profile as following %}
            <button class="btn btn-primary {% if not following %}follow-user{% else %}unfollow-user{% endif %}" id="{{ profile.pk }}">
              {% if not following %}
                Follow
              {% else %}
                Following
              {% endif %}
            </button>
          </div>
          {% endif %}
          <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <ul>
                  <li><a type="button" class="btn" href="">Change Password</a></li>
                  <li><a type="button" class="btn" href="{% url 'signout' %}">Logout</a></li>
                  <li><a type="button" class="btn" data-dismiss="modal">Cancel</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        {% if request.user == user %}
          <a class="edit-mobile" href="{% url 'profile_settings' user.username %}">
            <button class="edit-profile">Edit Profile</button>
          </a>
        {% endif %}
        <div class="desktop-block">
          <ul class="stats">
              <li class="stats__count"><span>{{ profile.igpost_set.count }}</span> Posts</li>
              <a href="{% url 'followers' username=profile.user.username %}"><li class="stats__count"><span>{{ profile.get_number_of_followers }}</span> Followers</li></a>
              <a href="{% url 'following' username=profile.user.username %}"><li class="stats__count"><span>{{ profile.get_number_of_following }}</span> Following</li></a>
          </ul>
          <div class="description">
            <p>{% if profile.description %}{{ profile.description }}{% endif %}</p>
          </div>
        </div>
      </div>
      <div class="mobile-block">
        <div class="description">
          <p>{% if profile.description %}{{ profile.description }}{% endif %}</p>
        </div>
        <ul class="stats">
            <div class="col-xs-4"><li class="stats__count"><span>{{ profile.igpost_set.count }}</span><br> posts</li></div>
            <div class="col-xs-4"><a href="{% url 'followers' username=profile.user.username %}"><li class="stats__count"><span>{{ profile.get_number_of_followers }}</span><br> followers</li></a></div>
            <div class="col-xs-4"><a href="{% url 'following' username=profile.user.username %}"><li class="stats__count"><span>{{ profile.get_number_of_following }}</span><br> following</li></a></div>
        </ul>
      </div>
    </div>
  </div>

  <div class="profile__body">
    <div class="row">
      {% for post in profile.igpost_set.all reversed %}
        <div class="col-xs-4">
          <div class="picture-square" style="background-image: url({{ post.image.url }})">
            <a href="{% url 'post' post.pk %}">
              <div class="content">
                <i class="fa fa-heart" aria-hidden="true"></i> {{ post.get_number_of_likes }}
                <i class="fa fa-comment" aria-hidden="true"></i> {{ post.get_number_of_comments }}
              </div>
            </a>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>

</div>

{% endblock %}

django_instagram/feeds/templates/feeds/signup_success.html
{% extends 'feeds/base.html' %}

{% block content %}
    <div class="row">
        <p class="success-message">
            Welcome to DjangoIG {{ user.username }}
        </p>
    </div>
{% endblock %}